### ISSUE TITLE
UI issues with new UX

### ISSUE THREAD

**Issue by Shaulbm** [Claro-Mentor/moovNowMVP#690]
1, In mobile view - 
<img width="385" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1FQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad36fc63e34ef225b7d30661dc6282a7f9b91999/image.png" alt="image.png" />

please fix this to be:
<img width="374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dac6fa802c6b93242409ab75f920ab51f73bbca/image.png" alt="image.png" />

2. in mobile view - this is the appearance of the menu, please have the image stick to the bottom:
<img width="296" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e4dbcd9a42f4e0244b387ee912cdce2a13fb861/image.png" alt="image.png" />

3. When in low resolution:
<img width="1217" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm9FQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71029cb9ac3360bdeca19e8ae83a42e0e8bab57f/image.png" alt="image.png" />

**Comment by NoamRivlin** [comment]
1. 
are you sure you want the hamburger menu on the left?
the figma is like I did, like this:
<img width="1836" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ce557160e724b8da9240e6e74d32386c9b52272/image.png" alt="image.png" />

3.
this is due to the sidebar ? or just the user profile is broken

**Comment by Shaulbm** [comment]
fixed
